### ISSUE TITLE
请问userwords.txt在哪里？

### ISSUE THREAD

**Issue by betsyalan** [1158114251/-Intelligent-speech-robot#1]
你好，下了你的代码，发现没有userwords.txt这个文件，是否可以传上来？谢谢。

**Comment by 1158114251** [comment]
没有用到userwords.txt

**Comment by icestoneking** [comment]
楼主你好，我正在linux上实现一个音频可视化工具，但是报错和你一篇博客的错误类似，
sed_visualizer
  Audio file                        : ./tests/data/a001.wav 
  Event lists
    ID   Label          Event list file                         
    0    reference      ./tests/data/a001.ann                  
    1    system         ./tests/data/a001_system_output.ann    
  Mode                              : None 
  Active events                     : None 
  Publication mode                  : False 
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Colormap spectral is not recognized. Possible values are: Accent, Accent_r, Blues, 
用了你写的方法还是有问题，请问是不是我们问题不一样呢，如果不是pyaudio的问题我在尝试一下其他方法，期待您的回复～谢谢～

**Comment by 1158114251** [comment]
你是基于python的吗，这个问题其实不是什么大问题，如果程序已经正常工作。主要是修由于/usr/share/alsa/alsa.conf 文件的配置引起，如果是py你也可以，

from ctypes import *
from contextlib import contextmanager
import pyaudio

ERROR_HANDLER_FUNC = CFUNCTYPE(None, c_char_p, c_int, c_char_p, c_int, c_char_p)

def py_error_handler(filename, line, function, err, fmt):
    pass

c_error_handler = ERROR_HANDLER_FUNC(py_error_handler)

@contextmanager
def noalsaerr():
    asound = cdll.LoadLibrary('libasound.so')
    asound.snd_lib_error_set_handler(c_error_handler)
    yield
    asound.snd_lib_error_set_handler(None)
After doing this you can re-use the error handler by using the noalsaerr context:

with noalsaerr():
    p = pyaudio.PyAudio()
stream = p.open(format=pyaudio.paFloat32, channels=1, rate=44100, output=1)

**Comment by icestoneking** [comment]
是基于Python的，我看了你博客上面写的更改alsa.conf文件配置的方法了，是把报错的代码都删掉吗？如果只是类似于警告的那种报错还可以理解，现在这个问题影响音频的可视化，你写的代码加在里面好像还是不行，也有说是portaudio的问题

**Comment by icestoneking** [comment]
在进行这步的时候sudo apt-get install libportaudio0 libportaudio2 libportaudiocpp0 portaudio19-dev，这个libportaudio0没有安装成功～
